version: '3'

services:
  nginx:
    image: nginx
    container_name: web-nginx-container
    ports:
      - "8088:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
  node:
    image: node:alpine
    container_name: web-node-container
    working_dir: /app
    volumes:
      - ".:/app"
    command: npm run start
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: web-mysql-container
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD:docker
      - MYSQL_DATABASE:docker
      # - MYSQL_USER:docker
      # - MYSQL_PASSWORD:docker
    